# Suppress R CMD check NOTEs for data.table NSE bindings
utils::globalVariables(c(
  ".", ".N", ".SD", ".data", ":=",
  "..activity_cols", "..cols_needed", "..coord_cols", "..out_cols",
  "N", "NES",
  "activity", "artifact_flag", "barcode",
  "category", "cell_id", "cell_type", "ci_hi", "ci_lo", "classification",
  "coef", "coef_ratio", "combined_coef", "combined_score", "condition",
  "count", "decay_pattern", "direct_score", "direction",
  "dist_to_control", "dist_to_query",
  "enrichment_score",
  "fdr", "fdr_fisher", "fisher_fdr", "fisher_pval",
  "gene", "gene_safe", "gradient_score",
  "is_broad", "is_combined", "is_query_marker", "is_sig", "is_target",
  "leadingEdge", "ligand", "ligand_pct_query", "lower",
  "mean_abs_nes", "mean_nes", "mean_val", "median_coef", "median_dispersion", "median_per_sample_score", "morans_i",
  "n_celltypes", "n_celltypes_strict", "n_control", "n_genes", "n_overlap", "n_query_cells", "n_samples", "ncells_sum",
  "neg_log10_fdr", "neg_log10_fdr_capped", "neg_log10_padj",
  "nichenet_activity",
  "obj", "odds_ratio",
  "padj", "pathway", "pathway_clean", "pct_expr", "perm_pval", "permutation_pool",
  "plot_color", "pval", "pvalue_fisher",
  "ratio", "receptor", "receptor_pct_target",
  "sample_id", "scaled_activity", "scaled_direct",
  "scaled_enrichment", "scaled_expression",
  "se", "se_val", "show_label", "sign_consistency", "significant", "spatial_x", "spatial_y",
  "specificity_class",
  "stage1_coef", "stage1_fdr",
  "stage2_fisher_fdr", "stage2_fisher_pval", "stage2_median_coef",
  "total", "type", "upper", "x", "y"
))
